services:
  crdb:
    image: cockroachdb/cockroach:latest
    restart: always
    ports:
      - ${DB_PORT}:26257
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "./cockroach-data:/cockroach/cockroach-data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      COCKROACH_DATABASE: ${DB_NAME}

  backend:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-8000}
    environment:
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/backend
          ignore:
            - tmp/
            - .git/
            - .air.toml
            - .gitignore
            - .dockerignore
            - cockroach-data/
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      crdb:
        condition: service_healthy
